M48
; DRILL file {KiCad 7.0.7} date Thu Sep 14 12:10:11 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-14T12:10:11+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.450
%
G90
G05
T1
X94.6Y-95.365
X94.6Y-100.215
T2
X91.57Y-95.065
X91.57Y-100.515
T3
X50.16Y-123.415
X73.66Y-123.415
T0
M30
